# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1niMPrSghUZwmvqXEVtqKRJW548v31sVg
"""

import pandas as pd

comb_df = pd.read_excel('ca-2021-02.xlsx')

print(comb_df)

display(comb_df)

#Exibe as primeiras cinco linhas
display(comb_df.head())

#Primeiras X linhas
display(comb_df.head(23))

#dataframe.info() colunas e tipos de dados cada um tem...
print(comb_df.info())

#Dataframe.shape e dataframe.describe()
linhas, colunas = comb_df.shape
print(f'{linhas} linhas e {colunas} colunas')
print(comb_df.describe())

display(comb_df['Revenda'].head(20))

#Cria novo dataframe apenas com colunas desejadas
ca_df = comb_df[['Revenda','Municipio','Estado - Sigla','Valor de Venda','Produto']]
display(ca_df.head(10))

#Funcao loc  "locate" 
#Exite linha 4
display(ca_df.loc[0])

display(ca_df.loc[9:19])

'''Criar dataframe gas_df contendo apenas 4 colunas (Revenda, Municipio,
Produto, Valor de Venda) somente com combustiel sendo GASOLINA'''
gas_df = ca_df.loc[ca_df['Produto'] == 'GASOLINA']
display(gas_df.max())

#Posto e municipio gasolina mais cara
display(gas_df[['Revenda','Municipio','Valor de Venda']].max())

display(gas_df[['Revenda', 'Municipio', 'Estado - Sigla', 'Valor de Venda']].max())

#Dataframe.loc com multiplas condições
#Quais são os preços,postos de ETANOL em INDAIATUBA em ordem crescente de preço
eta_indaiatuba_df = ca_df.loc[(ca_df['Produto'] == 'ETANOL') & (ca_df['Municipio'] == 'INDAIATUBA')]
eta_indaiatuba_df.sort_values(by='Valor de Venda', inplace=True)
display(eta_indaiatuba_df)

# Qual a média de preços dos combustiveis GASOLINA e GASOLINA ADITIVADA do bairro MOOCA em SÃO PAULO
display(comb_df.loc[(comb_df['Bairro'] == 'MOOCA') & 
                    (comb_df['Municipio'] == 'SAO PAULO') & 
                    (comb_df['Produto'].isin(["GASOLINA","GASOLINA ADITIVADA"])),
                    ['Valor de Venda']].mean())

# Como mostrar média de valor de venda Por Combustível
display(ca_df[['Produto','Valor de Venda']].groupby(by='Produto').mean().round(2))

#Adicionar coluna com bool chamada "Ativo" que por pad~roa vai ser True em todas as linhas
comb_df['Ativo'] = True
display(comb_df)

#Coluna nova Obs que preencha automaticamente melhor cidade quando municipio = INDAIATUBA
# comb_df['Obs'] = 'MELHOR CIDADE' if comb_df['Municipio'] == 'INDAIATUBA' else None

# Exportar para excel
eta_indaiatuba_df.to_excel('etanol_indaiatuba.xlsx',sheet_name='Etanol em Indaiatuba')