# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lu4wjJbFJ_dTqGIS0DBwUKwFsdQQgjJK
"""

import pandas as pd
comb_df = pd.read_excel('ca-2021-02.xlsx')
display(comb_df.head(10))

comb_df['Ativo'] = True

display(comb_df.head())

comb_df['Obs:'] = ['Melhor Estado' if estado == 'MG' else 'Horrível' for estado in comb_df['Estado - Sigla']]
display(comb_df[['Estado - Sigla','Obs:']].loc[comb_df['Estado - Sigla'].isin(['MG','SP'])].tail(10))

from numpy import where
comb_df['Status preco'] = where(comb_df['Valor de Venda'] > 6.5, 'Caro', 'Barato')
display(comb_df.head())
print(f'{(comb_df["Status preco"] == "Caro").sum()} com status de "Caro"')
print(f'{(comb_df["Status preco"] == "Barato").sum()} com status de "Barato"')

#Calcular postos de gasolina por habitante
num_habitantes_df = pd.read_csv('ibge_num_habitantes_estimado.csv',sep=';')
num_habitantes_df.rename(columns={'Estado':'Estado - Sigla'}, inplace=True)
display(num_habitantes_df)

colunas = ['Municipio','Estado - Sigla']
merge_df = comb_df.merge(num_habitantes_df, how="inner", on=colunas)
display(merge_df)
print(merge_df.info())

#Destruir coluna vazia
merge_df.dropna(axis=1,inplace=True)
print(merge_df.info())

colunas = ['Regiao - Sigla','Nome da Rua', 'Numero Rua','Bairro','Cep','Produto','Data da Coleta','Valor de Venda','Unidade de Medida','Bandeira','Obs:','Status preco']
merge_df.drop(labels=colunas,axis=1,inplace=True)
print(merge_df.info())

#remover postos repetidos
merge_df.drop_duplicates(inplace=True)
display(merge_df)
print(merge_df.info())

#Agrupa e conta postos
# postos_por_municipio_df = merge_df.groupby(by=['Estado - Sigla','Municipio','NumHabitantes2021']).count()
# postos_por_municipio_df.drop('CNPJ da Revenda',axis=1,inplace=True)
# postos_por_municipio_df.rename(columns={'Revenda':'Numero de Postos'},inplace=True)
# display(postos_por_municipio_df)
# print(posto_por_municipio_df.info())
# postos_por_municipio_df['Postos/Habitante'] = postos_por_municipio_df['Numero de Postos'] / postos_por_municipio_df['NumHabitantes2021']
# display(postos_por_municipio_df)